spring:
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.31.100:3306/shop?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: MyDifficultPass4@
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  redis:
    host: 127.0.0.1
  #  #配置mail信息
  mail:
    host: smtp.163.com
    username: kamisora2020@163.com
    password: VBWQMVCCRAHOFNDE
    port: 465
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
#配置mybatis-plus信息
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml